version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html    
hooks:
  BeforeInstall:
    - location: scripts/setup.sh
      timeout: 120
      runas: root  
  AfterInstall:
    - location: scripts/start.sh
      timeout: 120
      runas: root
